

//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http'; 
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import "rxjs/add/operator/toPromise";

    import * as Enums from '../classes/EnumDefinitions'
    import { Creature } from '../classes/Creature';

@Injectable()
export class CreaturesRepository {

    constructor(private _httpClient: HttpClient) { }        
    
    // get: api/Creature/getCreatures   

	//public getCreatures = (, callback: (data: Creature[])=>void) : void => {
	//	this.getCreaturesObserve().subscribe(response => callback(response));
	//}

	public getCreaturesAsync = () : Promise<Creature[]> => {
        
        return new Promise<Creature[]>((resolve, reject) => {
            this.getCreatures()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}  

	public getCreatures = () : Observable<Creature[]> => {
        var _Url = `api/Creature/getCreatures`;
            return this._httpClient.get<Creature[]>(_Url)
                .catch(this.handleError);
	};

    
    // get: api/Creature/getCreature?id=${id}   

	//public getCreature = (id: number, callback: (data: Creature)=>void) : void => {
	//	this.getCreatureObserve(id).subscribe(response => callback(response));
	//}

	public getCreatureAsync = (id: number) : Promise<Creature> => {
        
        return new Promise<Creature>((resolve, reject) => {
            this.getCreature(id)
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}  

	public getCreature = (id: number) : Observable<Creature> => {
        var _Url = `api/Creature/getCreature?id=${id}`;
            return this._httpClient.get<Creature>(_Url)
                .catch(this.handleError);
	};

    
    // post: api/Creature/saveCreature   

	//public saveCreature = (creature: Creature, callback: (data: Creature)=>void) : void => {
	//	this.saveCreatureObserve(creature).subscribe(response => callback(response));
	//}

	public saveCreatureAsync = (creature: Creature) : Promise<Creature> => {
        
        return new Promise<Creature>((resolve, reject) => {
            this.saveCreature(creature)
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}  

	public saveCreature = (creature: Creature) : Observable<Creature> => {
        var _Url = `api/Creature/saveCreature`;
            return this._httpClient.post(_Url, creature)
                .catch(this.handleError);
	};

    
    // delete: api/Creature/deleteCreature?id=${id}   

	//public deleteCreature = (id: number, callback: (data: void)=>void) : void => {
	//	this.deleteCreatureObserve(id).subscribe(response => callback(response));
	//}

	public deleteCreatureAsync = (id: number) : Promise<void> => {
        
        return new Promise<void>((resolve, reject) => {
            this.deleteCreature(id)
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}  

	public deleteCreature = (id: number) : Observable<void> => {
        var _Url = `api/Creature/deleteCreature?id=${id}`;
            return this._httpClient.delete(_Url)
                .catch(this.handleError);
	};

    
    // Utility
    private handleError(error: HttpErrorResponse) {
        console.error(error);
        let customError: string = "";
        if (error.error) {
            customError = error.status === 400 ? error.error : error.statusText
        }
        return Observable.throw(customError || 'Server error');
    }
}


	