//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace CombatTracker.Domain.Reference.Creatures.Charts
{
    [Table("Creature_LevelChartValues")]
    public partial class LevelChartValue
    {
        public int ID { get; set; }
        public int Level_ID { get; set; }
        public int Min { get; set; }
        public int Max { get; set; }
        public int Mod { get; set; }

        [ForeignKey("Level_ID")]
        public virtual LevelChart LevelChart { get; set; }
    }
    
}
