//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using CombatTracker.Domain.Reference.Base;

namespace CombatTracker.Domain.Reference.Creatures.Charts
{
    [Table("Creature_Pace")]
    public partial class Pace : ReferenceEntry
    {
        public Pace()
        {
            //this.Creatures = new HashSet<Creature>();
        }
    
        //public int ID { get; set; }
        //public string Name { get; set; }
        //public string Abbreviation { get; set; }
    
        //public virtual ICollection<Creature> Creatures { get; set; }


        public override string ToString()
        {
            return Name;
        }

        public static Pace LoadByName(RmssDbContext db, string name)
        {
            return (from sc in db.Paces where sc.Name == name select sc).FirstOrDefault();
        }
    }
    
}
