////------------------------------------------------------------------------------
//// <auto-generated>
////    This code was generated from a template.
////
////    Manual changes to this file may cause unexpected behavior in your application.
////    Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//using System;
//using System.Collections.Generic;
//using CombatTracker.Domain.Current;
//using CombatTracker.Domain.Reference.Attacks;
//using Action = CombatTracker.Domain.Reference.Actions.Action;

//namespace CombatTracker.Domain
//{
//    public partial class ActorsActionOld
//    {
        
    
        
//        public int Bleeder { get; set; }
//        public int Count { get; set; }
//        public Nullable<int> Critical_ID { get; set; }
//        public int TotalRounds { get; set; }
//        public int LevelDifference { get; set; }
//        public bool IsHasted { get; set; }
//        public bool IsSlowed { get; set; }
//        public double HastedPercent { get; set; }
    
        
//        public virtual CriticalAffect CriticalAffect { get; set; }
//    }
    
//}
