//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;
using CombatTracker.Entities.Reference.Base;

namespace CombatTracker.Entities.Reference.Attacks.Charts
{
    public partial class WeaponType : ReferenceEntry
    {

        public override string ToString()
        {
            return Name;
        }

        //public static WeaponType LoadByName(RmssDbContext db, string name)
        //{
        //    return (from sc in db.WeaponTypes where sc.Name == name select sc).FirstOrDefault();
        //}
    }
    
}
