//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;
using CombatTracker.Domain.Reference.Base;

namespace CombatTracker.Domain.Reference.Attacks.Charts
{
    public partial class WeaponType : ReferenceEntry
    {
        //public int ID { get; set; }
        //public string Name { get; set; }
        //public string Abbreviation { get; set; }


        public override string ToString()
        {
            return Name;
        }

        public static WeaponType LoadByName(RmssDbContext db, string name)
        {
            return (from sc in db.WeaponTypes where sc.Name == name select sc).FirstOrDefault();
        }
    }
    
}
