//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations.Schema;
using CombatTracker.Entities.Reference.Creatures;

namespace CombatTracker.Entities.Reference
{
    public partial class Book
    {
        public Book()
        {
            this.Creatures = new HashSet<Creature>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Creature> Creatures { get; set; }


        public override string ToString()
        {
            return Name;
        }
    }
    
}
