//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CombatTracker.Domain.Current;
using CombatTracker.Domain.Reference.Attacks;

namespace CombatTracker.Domain.Many2Many
{
    public partial class ActorsAttack
    {
        public int ID { get; set; }
        public int Actor_ID { get; set; }
        public int Attack_ID { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Attack Attack { get; set; }
    }
    
}
