//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CombatTracker.Domain.Current;

namespace CombatTracker.Domain.Many2Many
{
    public partial class GamesPlayer
    {
        public int ID { get; set; }
        public int Game_ID { get; set; }
        public System.Guid Player_ID { get; set; }
    
        public virtual Game Game { get; set; }
    }
    
}
