//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations.Schema;

namespace CombatTracker.Domain.Reference
{
    [Table("Armors")]
    public partial class Armor
    {
        public int ID { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public int MovingManeuverMod { get; set; }
        public int DB { get; set; }
        public int? BaseArmor_ID { get; set; }
        public int? TiedToID { get; set; }

        [ForeignKey("TiedToID")]
        public virtual Character Character { get; set; }

        [ForeignKey("BaseArmor_ID")]
        public virtual Armor ReferenceArmor { get; set; }


        public override string ToString()
        {
            return Type.ToString();
        }
    }
    
}
