//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace CombatTracker.Domain.Reference
{
    [Table("Weapon")]
    public partial class Weapon
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int MinWeight { get; set; }
        public int MaxWeight { get; set; }
        public int Weight { get; set; }
        public int Bonus { get; set; }
        public bool Is2Handed { get; set; }
        public int OB { get; set; }
        public int? TiedToID { get; set; }

        [ForeignKey("TiedToID")]
        public virtual Character Character { get; set; }


        public override string ToString()
        {
            return Name;
        }
    }
    
}
