//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using CombatTracker.Entities.Reference.Base;

namespace CombatTracker.Entities.Reference.Creatures.Charts
{
    public partial class CriticalIgnore : ReferenceEntry
    {
        public CriticalIgnore()
        {
            //this.Creatures = new HashSet<Creature>();
        }
    

        public override string ToString()
        {
            return Name;
        }
    }
    
}
