//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Action = CombatTracker.Domain.Reference.Actions.Action;

namespace CombatTracker.Domain
{
    public partial class ActionGroup
    {
        public ActionGroup()
        {
            this.Actions = new List<Action>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual IList<Action> Actions { get; set; }


        public override string ToString()
        {
            return Name;
        }
    }
    
}
