//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using CombatTracker.Domain.Current.Actions;
using CombatTracker.Domain.Reference;

namespace CombatTracker.Domain.Current
{
    public partial class CriticalAffect
    {
        public CriticalAffect()
        {
            this.Actions = new HashSet<CriticalAction>();
        }
    
        public int ID { get; set; }
        public bool IsStunned { get; set; }
        public ParryType Parry { get; set; }
        public int ParryNegative { get; set; }
        public int Negative { get; set; }
        public double TimeStart { get; set; }
        public double TimeEnd { get; set; }
        public int Actor_ID { get; set; }
    
        public virtual Actor Actor { get; set; }
        [InverseProperty("Critical_ID")]
        public virtual ICollection<CriticalAction> Actions { get; set; }
    }
    
}
