version: "3"

services:
    database:
        container_name: sql1
        image: "microsoft/mssql-server-linux"
        ports:
        - 5100:1433
        environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=mySecret123