


//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import {Observable, throwError} from "rxjs";
import { map, catchError } from "rxjs/operators";
import { AlertService } from '@/services/Alert.service';

    import * as Enums from '@/entities/EnumDefinitions'
    import { Game } from '@/entities';

var version = "1";

@Injectable({ providedIn: 'root' })
export class GamesRepository {

    constructor(private _httpClient: HttpClient, private _alertService: AlertService) { }
    
    // get: api/v${version}/Games/GetGames

	//public getGames = (, callback: (data: Game[])=>void) : void => {
	//	this.getGamesObserve().subscribe(response => callback(response));
	//}

	public getGamesAsync = () : Promise<Game[]> => {

        return new Promise<Game[]>((resolve, reject) => {
            this.getGames()
            .subscribe((res) => {
                    resolve(res);
                }, (error: string) => {
                    this._alertService.error(error);
                    resolve(null);
                });

        });
	}

	public getGames = () : Observable<Game[]> => {
        
            var _Url = `api/v${version}/Games/GetGames`;

            return this._httpClient.get<Game[]>(_Url)
                .pipe(
                        map((data) => {
                            if (data != null) data = data.map((dt) => Object.assign(new Game(), dt));
                            return data;
                        }), 
                        catchError(this.handleError)
                );
	};

    
    // get: api/v${version}/Games/GetGame/${id}

	//public getGame = (id: number, callback: (data: Game)=>void) : void => {
	//	this.getGameObserve(id).subscribe(response => callback(response));
	//}

	public getGameAsync = (id: number) : Promise<Game> => {

        return new Promise<Game>((resolve, reject) => {
            this.getGame(id)
            .subscribe((res) => {
                    resolve(res);
                }, (error: string) => {
                    this._alertService.error(error);
                    resolve(null);
                });

        });
	}

	public getGame = (id: number) : Observable<Game> => {
        id = (id == null ? <number><any>"" : id);
        
            var _Url = `api/v${version}/Games/GetGame/${id}`;

            return this._httpClient.get<Game>(_Url)
                .pipe(
                        map((data) => {
                            if (data != null) data = Object.assign(new Game(), data);
                            return data;
                        }), 
                        catchError(this.handleError)
                );
	};

    
    // post: api/v${version}/Games/SaveGame

	//public saveGame = (game: Game, callback: (data: Game)=>void) : void => {
	//	this.saveGameObserve(game).subscribe(response => callback(response));
	//}

	public saveGameAsync = (game: Game) : Promise<Game> => {

        return new Promise<Game>((resolve, reject) => {
            this.saveGame(game)
            .subscribe((res) => {
                    resolve(res);
                }, (error: string) => {
                    this._alertService.error(error);
                    resolve(null);
                });

        });
	}

	public saveGame = (game: Game) : Observable<Game> => {
        game = (game == null ? <Game><any>"" : game);
        
            var _Url = `api/v${version}/Games/SaveGame`;

            return this._httpClient.post<Game>(_Url, game)
                .pipe(
                        map((data) => {
                            if (data != null) data = Object.assign(new Game(), data);
                            return data;
                        }), 
                        catchError(this.handleError)
                );
	};

    
    // delete: api/v${version}/Games/DeleteGame/${id}

	//public deleteGame = (id: number, callback: (data: void)=>void) : void => {
	//	this.deleteGameObserve(id).subscribe(response => callback(response));
	//}

	public deleteGameAsync = (id: number) : Promise<void> => {

        return new Promise<void>((resolve, reject) => {
            this.deleteGame(id)
            .subscribe((res) => {
                    resolve(res);
                }, (error: string) => {
                    this._alertService.error(error);
                    resolve(null);
                });

        });
	}

	public deleteGame = (id: number) : Observable<void> => {
        id = (id == null ? <number><any>"" : id);
        
            var _Url = `api/v${version}/Games/DeleteGame/${id}`;

            return this._httpClient.delete<void>(_Url)
                .pipe(
                        map((data) => {
                            
                            return data;
                        }), 
                        catchError(this.handleError)
                );
	};

    
    // Utility
    private handleError(error: HttpErrorResponse) {
        
        //debugger;
        console.debug("handleError:" + error);
        //console.error(error);
        let customError: string = "";
        if (error.message) {
            customError = error.message; // error.status === 400 ? error.error : error.statusText
        }
        return throwError(customError || 'Server error');
        //return Observable.throw(customError || 'Server error');
    }
}






