


//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import {Observable, throwError} from "rxjs";
import { map, catchError } from "rxjs/operators";

    import * as Enums from '@/entities/EnumDefinitions'
    import { ActionGroup } from '@/entities';
import { ActionDefinition } from '@/entities';
import { ConstitutionBonusChart } from '@/entities';
import { CriticalCode } from '@/entities';
import { CriticalIgnore } from '@/entities';
import { IQ } from '@/entities';
import { LevelChart } from '@/entities';
import { Outlook } from '@/entities';
import { Pace } from '@/entities';
import { SizeRating } from '@/entities';
import { SpeedChart } from '@/entities';
import { AttackType } from '@/entities';
import { CriticalType } from '@/entities';
import { WeaponType } from '@/entities';
import { Book } from '@/entities';
import { PsychicRefractoryPeriodEntry } from '@/entities';

var version = "1.0";

@Injectable({ providedIn: 'root' })
export class ReferenceRepository {

    constructor(private _httpClient: HttpClient) { }
    
    // get: api/v${version}/Reference/getActionGroups

	//public getActionGroups = (, callback: (data: ActionGroup[])=>void) : void => {
	//	this.getActionGroupsObserve().subscribe(response => callback(response));
	//}

	public getActionGroupsAsync = () : Promise<ActionGroup[]> => {

        return new Promise<ActionGroup[]>((resolve, reject) => {
            this.getActionGroups()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getActionGroups = () : Observable<ActionGroup[]> => {
        
        var _Url = `api/v${version}/Reference/getActionGroups`;
            return this._httpClient.get<ActionGroup[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getActions?groupId=${groupId}

	//public getActions = (groupId: number, callback: (data: ActionDefinition[])=>void) : void => {
	//	this.getActionsObserve(groupId).subscribe(response => callback(response));
	//}

	public getActionsAsync = (groupId: number) : Promise<ActionDefinition[]> => {

        return new Promise<ActionDefinition[]>((resolve, reject) => {
            this.getActions(groupId)
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getActions = (groupId: number) : Observable<ActionDefinition[]> => {
        groupId = (groupId == null ? <number><any>"" : groupId);
        
        var _Url = `api/v${version}/Reference/getActions?groupId=${groupId}`;
            return this._httpClient.get<ActionDefinition[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getConstitutionBonusCharts

	//public getConstitutionBonusCharts = (, callback: (data: ConstitutionBonusChart[])=>void) : void => {
	//	this.getConstitutionBonusChartsObserve().subscribe(response => callback(response));
	//}

	public getConstitutionBonusChartsAsync = () : Promise<ConstitutionBonusChart[]> => {

        return new Promise<ConstitutionBonusChart[]>((resolve, reject) => {
            this.getConstitutionBonusCharts()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getConstitutionBonusCharts = () : Observable<ConstitutionBonusChart[]> => {
        
        var _Url = `api/v${version}/Reference/getConstitutionBonusCharts`;
            return this._httpClient.get<ConstitutionBonusChart[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getCriticalCodes

	//public getCriticalCodes = (, callback: (data: CriticalCode[])=>void) : void => {
	//	this.getCriticalCodesObserve().subscribe(response => callback(response));
	//}

	public getCriticalCodesAsync = () : Promise<CriticalCode[]> => {

        return new Promise<CriticalCode[]>((resolve, reject) => {
            this.getCriticalCodes()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getCriticalCodes = () : Observable<CriticalCode[]> => {
        
        var _Url = `api/v${version}/Reference/getCriticalCodes`;
            return this._httpClient.get<CriticalCode[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getCriticalIgnores

	//public getCriticalIgnores = (, callback: (data: CriticalIgnore[])=>void) : void => {
	//	this.getCriticalIgnoresObserve().subscribe(response => callback(response));
	//}

	public getCriticalIgnoresAsync = () : Promise<CriticalIgnore[]> => {

        return new Promise<CriticalIgnore[]>((resolve, reject) => {
            this.getCriticalIgnores()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getCriticalIgnores = () : Observable<CriticalIgnore[]> => {
        
        var _Url = `api/v${version}/Reference/getCriticalIgnores`;
            return this._httpClient.get<CriticalIgnore[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getIQs

	//public getIQs = (, callback: (data: IQ[])=>void) : void => {
	//	this.getIQsObserve().subscribe(response => callback(response));
	//}

	public getIQsAsync = () : Promise<IQ[]> => {

        return new Promise<IQ[]>((resolve, reject) => {
            this.getIQs()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getIQs = () : Observable<IQ[]> => {
        
        var _Url = `api/v${version}/Reference/getIQs`;
            return this._httpClient.get<IQ[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getLevelCharts

	//public getLevelCharts = (, callback: (data: LevelChart[])=>void) : void => {
	//	this.getLevelChartsObserve().subscribe(response => callback(response));
	//}

	public getLevelChartsAsync = () : Promise<LevelChart[]> => {

        return new Promise<LevelChart[]>((resolve, reject) => {
            this.getLevelCharts()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getLevelCharts = () : Observable<LevelChart[]> => {
        
        var _Url = `api/v${version}/Reference/getLevelCharts`;
            return this._httpClient.get<LevelChart[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getOutlooks

	//public getOutlooks = (, callback: (data: Outlook[])=>void) : void => {
	//	this.getOutlooksObserve().subscribe(response => callback(response));
	//}

	public getOutlooksAsync = () : Promise<Outlook[]> => {

        return new Promise<Outlook[]>((resolve, reject) => {
            this.getOutlooks()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getOutlooks = () : Observable<Outlook[]> => {
        
        var _Url = `api/v${version}/Reference/getOutlooks`;
            return this._httpClient.get<Outlook[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getPaces

	//public getPaces = (, callback: (data: Pace[])=>void) : void => {
	//	this.getPacesObserve().subscribe(response => callback(response));
	//}

	public getPacesAsync = () : Promise<Pace[]> => {

        return new Promise<Pace[]>((resolve, reject) => {
            this.getPaces()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getPaces = () : Observable<Pace[]> => {
        
        var _Url = `api/v${version}/Reference/getPaces`;
            return this._httpClient.get<Pace[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getSizeRatings

	//public getSizeRatings = (, callback: (data: SizeRating[])=>void) : void => {
	//	this.getSizeRatingsObserve().subscribe(response => callback(response));
	//}

	public getSizeRatingsAsync = () : Promise<SizeRating[]> => {

        return new Promise<SizeRating[]>((resolve, reject) => {
            this.getSizeRatings()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getSizeRatings = () : Observable<SizeRating[]> => {
        
        var _Url = `api/v${version}/Reference/getSizeRatings`;
            return this._httpClient.get<SizeRating[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getSpeedCharts

	//public getSpeedCharts = (, callback: (data: SpeedChart[])=>void) : void => {
	//	this.getSpeedChartsObserve().subscribe(response => callback(response));
	//}

	public getSpeedChartsAsync = () : Promise<SpeedChart[]> => {

        return new Promise<SpeedChart[]>((resolve, reject) => {
            this.getSpeedCharts()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getSpeedCharts = () : Observable<SpeedChart[]> => {
        
        var _Url = `api/v${version}/Reference/getSpeedCharts`;
            return this._httpClient.get<SpeedChart[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getAttackTypes

	//public getAttackTypes = (, callback: (data: AttackType[])=>void) : void => {
	//	this.getAttackTypesObserve().subscribe(response => callback(response));
	//}

	public getAttackTypesAsync = () : Promise<AttackType[]> => {

        return new Promise<AttackType[]>((resolve, reject) => {
            this.getAttackTypes()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getAttackTypes = () : Observable<AttackType[]> => {
        
        var _Url = `api/v${version}/Reference/getAttackTypes`;
            return this._httpClient.get<AttackType[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getCriticalTypes

	//public getCriticalTypes = (, callback: (data: CriticalType[])=>void) : void => {
	//	this.getCriticalTypesObserve().subscribe(response => callback(response));
	//}

	public getCriticalTypesAsync = () : Promise<CriticalType[]> => {

        return new Promise<CriticalType[]>((resolve, reject) => {
            this.getCriticalTypes()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getCriticalTypes = () : Observable<CriticalType[]> => {
        
        var _Url = `api/v${version}/Reference/getCriticalTypes`;
            return this._httpClient.get<CriticalType[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getWeaponTypes

	//public getWeaponTypes = (, callback: (data: WeaponType[])=>void) : void => {
	//	this.getWeaponTypesObserve().subscribe(response => callback(response));
	//}

	public getWeaponTypesAsync = () : Promise<WeaponType[]> => {

        return new Promise<WeaponType[]>((resolve, reject) => {
            this.getWeaponTypes()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getWeaponTypes = () : Observable<WeaponType[]> => {
        
        var _Url = `api/v${version}/Reference/getWeaponTypes`;
            return this._httpClient.get<WeaponType[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getBooks

	//public getBooks = (, callback: (data: Book[])=>void) : void => {
	//	this.getBooksObserve().subscribe(response => callback(response));
	//}

	public getBooksAsync = () : Promise<Book[]> => {

        return new Promise<Book[]>((resolve, reject) => {
            this.getBooks()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getBooks = () : Observable<Book[]> => {
        
        var _Url = `api/v${version}/Reference/getBooks`;
            return this._httpClient.get<Book[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // get: api/v${version}/Reference/getPsychicRefractoryPeriodEntries

	//public getPsychicRefractoryPeriodEntries = (, callback: (data: PsychicRefractoryPeriodEntry[])=>void) : void => {
	//	this.getPsychicRefractoryPeriodEntriesObserve().subscribe(response => callback(response));
	//}

	public getPsychicRefractoryPeriodEntriesAsync = () : Promise<PsychicRefractoryPeriodEntry[]> => {

        return new Promise<PsychicRefractoryPeriodEntry[]>((resolve, reject) => {
            this.getPsychicRefractoryPeriodEntries()
            .subscribe((res) => {
                    resolve(res);
                });

        });
	}

	public getPsychicRefractoryPeriodEntries = () : Observable<PsychicRefractoryPeriodEntry[]> => {
        
        var _Url = `api/v${version}/Reference/getPsychicRefractoryPeriodEntries`;
            return this._httpClient.get<PsychicRefractoryPeriodEntry[]>(_Url)
                .pipe(catchError(this.handleError));
	};

    
    // Utility
    private handleError(error: HttpErrorResponse) {
        console.error(error);
        let customError: string = "";
        if (error.error) {
            customError = error.status === 400 ? error.error : error.statusText
        }
        return Observable.throw(customError || 'Server error');
    }
}




