


//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import {Observable, throwError} from "rxjs";
import { map, catchError } from "rxjs/operators";
import { AlertService } from '@/services/Alert.service';

    import * as Enums from '@/entities/EnumDefinitions'
    

var version = "1";

@Injectable({ providedIn: 'root' })
export class SettingsRepository {

    constructor(private _httpClient: HttpClient, private _alertService: AlertService) { }
    
    // Utility
    private handleError(error: HttpErrorResponse) {
        
        //debugger;
        console.debug("handleError:" + error);
        //console.error(error);
        let customError: string = "";
        if (error.message) {
            customError = error.message; // error.status === 400 ? error.error : error.statusText
        }
        return throwError(customError || 'Server error');
        //return Observable.throw(customError || 'Server error');
    }
}






